# Generated by Django 4.2.17 on 2025-01-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='form',
            name='text',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
